### ISSUE TITLE
Scheduler choice

### ISSUE THREAD

**Issue by pgherveou** [sunshinejr/Moya-ModelMapper#12]
Hi there
I was looking at the code of this extension and was wondering if you could explain why you chose to use a SerialDispatchQueueScheduler [here](https://github.com/sunshinejr/Moya-ModelMapper/blob/master/Source/RxSwift/Observable%2BModelMapper.swift#L21 ):

Why is this a better choice than a ConcurrentDispatchQueueScheduler?

**Comment by sunshinejr** [comment]
Hey there @pgherveou! Hmm, no idea as of now, but indeed mapping probably will be better on a concurrent scheduler. It should be now changed in the newest version. Thanks! 🙇
