### ISSUE TITLE
Is this updated for the latest moya support version beta 8.0.0 beta 5?

### ISSUE THREAD

**Issue by rlam3** [sunshinejr/Moya-ModelMapper#17]
Is this updated for the latest moya support version beta 8.0.0 beta 5?

**Comment by Maxim-Inv** [comment]
I have made changes in the fork, you can use it in your podfile until my pull request will be accepted:
pod 'Moya-ModelMapper/RxSwift', :git => 'https://github.com/Maxim-Inv/Moya-ModelMapper'

**Comment by Maxim-Inv** [comment]
This repo have already updated.

**Comment by sunshinejr** [comment]
Right! I will do the release asap :)
