### ISSUE TITLE
RealmSwift

### ISSUE THREAD

**Issue by Niphery** [sunshinejr/Moya-ModelMapper#18]
Is there a way to make this work with Realm?
At the moment Realm use ObjectMapper which also implement the Mappable protocol.
Would it be possible to have them work together?

I've attempted to use the transform struct to create my own conversion without luck so far.

```
public static func transformToList<T: Object>() -> (_ object: Any) throws -> List<T> where T: Mappable
	{
		return { object in
			guard let objects = object as? [String: Any] else {
				throw MapperError.convertibleError(value: object, type: Any.self)
			}

			var result = List<T>()
			for entry in objects {
				let model = try! T(map: Mapper(JSON: entry))
				result.append(model)
			}

			return result
		}
	}

```
for some reasons the `let model = try! T(map: Mapper(JSON: entry))` method isn't recognize.

**Comment by sunshinejr** [comment]
This is a really old one, sorry I couldn't reach faster. I'm gonna close it for now, but if it still happens, please open a new issue.
