### ISSUE TITLE
New Release? 

### ISSUE THREAD

**Issue by rlam3** [sunshinejr/Moya-ModelMapper#21]
New Release?

I've been trying to get transform to work. but I think the new model mapper did some changes to how it is being returned. Thanks!

**Comment by sunshinejr** [comment]
Hey @rlam3, yes it is on my priority list and will be done this weekend with the new release of Moya as well.

**Comment by sunshinejr** [comment]
New version is release, if you find any troubles please create a new issue, thanks!
