### ISSUE TITLE
iOS version 8.0

### ISSUE THREAD

**Issue by eligat** [sunshinejr/Moya-ModelMapper#23]
I have a problem with my not-too-old project updating to Swift 3.0.

The only dependancy that cannot be satisfied is the Moya-ModelMapper requiring minimum deployment target of 9.0 for iOS.
Looking through the .podspec file I cannot find any reason for this, because Moya and ModelMapper both require minimum deployment target of 8.0 for iOS. OSX minimum deployment target also could be lowered to 10.10

Maybe there is something that requires iOS 9.0. Could you confirm, please?

**Comment by sunshinejr** [comment]
Hey @eligat, it should be now possible with 4.1.0 release. Totally forgot about it in the 4.0.0 so that's why 4.0.0 is still using iOS 9.0 & macOS 10.11. It was higher because Alamofire had it higher in their newest version, but they lowered it down. Sorry for inconvenience!
