### ISSUE TITLE
Conforming to the Swift API Guidelines.

### ISSUE THREAD

**Issue by sunshinejr** [sunshinejr/Moya-ModelMapper#27]
So I didn't really have time to check all the functions for proper conformation to new Swift API Guidelines, and because of #26 we will have another major bump, so this is the best time to make a PR with naming changes in the functions. If anyone is up for a starter task, [this](https://swift.org/documentation/api-design-guidelines/) is the link to the guidelines I'm talking about.

**Comment by gperdomor** [comment]
@sunshinejr i made a new mapper for a personal project, which i think conforms the swift guidelines... My idea is not replace your bundle or pod, but if you like, we can merge both repos :D...

let me know what you think :D

**Comment by sunshinejr** [comment]
We will do this for 5.0 release.

**Comment by sunshinejr** [comment]
This is in version 5.0.0 released today!
