### ISSUE TITLE
"Missing argument for parameter 'transformation' in call"

### ISSUE THREAD

**Issue by The0racle** [sunshinejr/Moya-ModelMapper#30]
Hi!

Every time I try to map to a NSNumber value, it gives me this error. For example:

```
struct User: Mappable {

let userId: NSNumber

init(map: Mapper){
   try userId = map.from("user_id")
}
```

If I changed the property from NSNumber to Int, it works fine. Am I missing something here?

**Comment by sunshinejr** [comment]
Not sure about this one. Also, this is a Mapper problem, rather than our Moya-ModelMapper connection. Please make an issue there if its still happening. Thanks for understanding 👍
