### ISSUE TITLE
Map object types

### ISSUE THREAD

**Issue by Aragunz** [sunshinejr/Moya-ModelMapper#31]
Ho do i map objects like this :

```
let kStreamFeedEntry    = "feed_entry"
let kStreamPrediction   = "prediction"
let kStreamMetadata     = "metadata"

struct FPStream : Mappable {

    var streamFeedEntry:FPFeedEntry
    
    init(map: Mapper) throws {
        try streamFeedEntry = map.from(kStreamFeedEntry)
    }
}
```
Please help me, im pretty new to Rx and im having a difficult time, you are lifesaver, if it wasnt for u i wouldnt reach this far. Thank you

**Comment by sunshinejr** [comment]
Hey @Aragunz. Sorry for the wait. Please let me know what is the JSON string you got and I will try to help you in this one :)

**Comment by sunshinejr** [comment]
Closing this one due to inactivity. If you still encounter the issue, please post a JSON payload & mapper model you are trying to map to. Thanks!
