### ISSUE TITLE
Update Release Version and add Carthage to README

### ISSUE THREAD

**Issue by lswith** [sunshinejr/Moya-ModelMapper#33]
We should update the release version now that carthage is available. We should also add carthage install to the README.

**Comment by sunshinejr** [comment]
Good point. I'm gonna try to release new version soon. Would you be up for updating the Readme, @lswith?

**Comment by lswith** [comment]
Sure

**Comment by sunshinejr** [comment]
Both done. Thank you so much @lswith! If problems with Carthage persist, #6 is for that one.
