### ISSUE TITLE
Rx extensions broken?

### ISSUE THREAD

**Issue by spookyvision** [sunshinejr/Moya-ModelMapper#42]
The source files `Single+ModelMapper.swift` (and `ObservableAvailability.swift`) are not included in the Moya-ModelMapper Xcode project. As a consequence, `.mapOptional(to:keyPath:)` is not found. (I can work around this by copying `Response+ModelMapper.swift` and `Single+ModelMapper.swift` to my own project instead of linking the Moya-ModelMapper framework)

<img width="262" alt="screen shot 2017-09-13 at 02 08 24" src="https://user-images.githubusercontent.com/45840/30353789-82ee0300-9828-11e7-936a-dd233ee4b0f8.png">

**Comment by sunshinejr** [comment]
Hey @spookyvision. Thanks for the issue and sorry for the problem! 

Do you use Carthage? I've linked the files in the xcodeproj and recreated the 5.0.0 tag which should fix that one. Please try it again when you have some free time and let me know if it works.

**Comment by spookyvision** [comment]
Yes, carthage user here. Thanks for the update! I'll try asap.

**Comment by sunshinejr** [comment]
Closing as it should be resolved in 5.0.0 and following 6.0.0-beta.1
