### ISSUE TITLE
macOS, etc. support

### ISSUE THREAD

**Issue by xaverlohmueller** [sunshinejr/Moya-ModelMapper#43]
This should be doable since all dependencies have support for macOS, watchOS, tvOS and iOS.

I have a [fork](https://github.com/xaverlohmueller/Moya-ModelMapper/commit/ee1e5026d9c96d310342d447931b164df57507d8) with some Works on my Machine™ code that my Carthage setup is happy with. I can submit a pull request if you want.

Notice, however, that I'm by no means a cross platform cocoapod/carthage/swiftpm expert and only tested this with Carthage.

**Comment by sunshinejr** [comment]
It should be up in 6.0.0-beta.1. Closing this one now, but if anything pops out, don't hesitate to reopen it again!
