### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by rlam3** [sunshinejr/Moya-ModelMapper#44]
Swift 4 support? @sunshinejr Was wonderingwhat the progress on this is. Thanks!

**Comment by sunshinejr** [comment]
Hey @rlam3, once we got Moya up and running for Swift 4 (which should be today/tomorrow), I will take care of new version of Moya-ModelMapper as well!

**Comment by rlam3** [comment]
@sunshinejr Thanks so much!! Really looking forward to this new upgrade! Please also include a memo of the breaking changes moving forward to swift 4 if possible!

**Comment by rlam3** [comment]
@sunshinejr was wondering if you had the chance to upgrade this for swift 4 yet. :) thanks!

**Comment by sunshinejr** [comment]
Hey @rlam3, it might be possible that I will do it today, but no promises :) Otherwise this week for sure!

**Comment by sunshinejr** [comment]
@rlam3 I released 6.0.0-beta.1, let me know if it works for you!

**Comment by rlam3** [comment]
Is this supposed to work with moya 9 or moya 10? @sunshinejr Thanks for your hard work!

**Comment by sunshinejr** [comment]
Hey @rlam3! 6.0.0-beta.1 should be available with Moya 10.0.0-beta.1 and for Moya 9.* you should use Moya-ModelMapper 5.0.0.

**Comment by rlam3** [comment]
Thanks @sunshinejr Looks like beta is finished and ready. Would love to get the v10 of Moya. Please update your dependencies for this package! Thanks!

**Comment by sunshinejr** [comment]
@rlam3 will do it today, sorry for the delay.

**Comment by sunshinejr** [comment]
It should be up now on all of the package managers (SPM, Carthage, CocoaPods). 🎉  

I'm closing the issue, but let me know if there are any problems with it!
