### ISSUE TITLE
Json parsing without array name

### ISSUE THREAD

**Issue by lnkien** [sunshinejr/Moya-ModelMapper#5]
I have a Json Array as string without name and I want to parse it how can i do it i ? Thank you.

["abc","def","123","456", "890"].

**Comment by sunshinejr** [comment]
Hey! Thanks for filling in the issue. 🎉 

Unfortunately you cannot do this right away using our library. If the string is really a JSON array (meaning it has JSON format), you can do the following:

1. Parse the object as a String, e.g. using `mapObject()`.
2. When you have the object parsed, let's say with a name `object`, now you can parse it to data using `NSJSONSerialization`. Like:
```swift
NSJSONSerialization.dataWithJSONObject(object, options: .PrettyPrinted)
```

Hope it helps!
