### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by philipengberg** [sunshinejr/Moya-ModelMapper#66]
Are there any roadmap decisions on Swift 5 support? Would be awesome with some beta releases that targets the corresponding [Moya beta releases](https://github.com/Moya/Moya/releases) and Swift 5 releases of sub dependencies like RxSwift.

**Comment by sunshinejr** [comment]
Hey @philipengberg. I have this on my todo list but I'm really swamped with the releases of Moya / SwiftyUserDefaults. I'll try to get to this as soon as possible, sorry for the delay.

**Comment by sunshinejr** [comment]
Hey @philipengberg, I just released 10.0.0-beta.1 that is compatible with the newest Moya 14.0.0-beta.4 version. Please reopen the issue if you're still having problems or create a new one if something happened after the upgrade. Thanks!
