### ISSUE TITLE
Issues mapping Int's

### ISSUE THREAD

**Issue by paul301** [sunshinejr/Moya-ModelMapper#7]
Trying to map Int but not working. Here is my Mapper:

```
import Mapper
struct Login: Mappable {
    let accessToken: String
    let expirationDate: String
    let userId: Int
    
    init(map: Mapper) throws {
        try accessToken = map.from("access_token")
        try expirationDate = map.from(".expires")
        try userId = map.from("userId")
    }
}
```

Here is my response as caught from NetworkLoggerPlugin:

`{
  "userId" : "2",
  ".issued" : "Sat, 06 Aug 2016 15:59:19 GMT",
  ".expires" : "Fri, 04 Nov 2016 15:59:19 GMT",
  "token_type" : "bearer",
  "access_token" : "R7fVvk8yvjTvQZZAg1-jmzTeANcQ2MEbqZ7CryoCAa4dVBxY4BdBU5BXH-h9lD6WR0tNYCCGJygEKztsfXkEdjq-CUnnV4ZVbdU6aeXVrb4CP7qeHi8T-tSDaL9hde0BXM_rwm9woowNczF-6mKq6zpwLrIJebBCm83fVNLJUUalmLoxR7yZdumW_ssRoJAyAxQKCXaNWj5vVX08lEyif5nQwZYLchouECO_MljMcT7Et727BUHzu3yTz1bsSdSsLLXERhd_Jfkf2Ch8RnAA6BX2zMM4XLowCRgmyf0MwsMTpIfBsroZi-VwLFrS6iNEOOneyVfotHd9k7bdPxrJiT3IMXjWheE_h2PzxNc-khYTjelnrv2JiXNcVtaLdyD5NFodA4syjeIyc8DcLpYugNU8D9sPeM-PmO5JsIMRU2LUC07XgldsfVquUae07dlHgY6MbPnMcV5-0aFtTVV496wxFlhE37G5ptaa_IM",
  "expires_in" : 7775999
}`

This is the request:

```
loginResponse = input.loginTaps.flatMapLatest{ _ -> Observable<Login?> in
            return input.provider.request(.Login(email: "pau6l", password: "Password1!")).mapObjectOptional(Login.self)
        }
```

The response ends up being nil. As soon as I change from Int to String, everything works. As a side note any easy way to map dates? would be nice to map that .expires

**Comment by paul301** [comment]
Pretty sure I've figured it out, the userId in this case is a string "userId" : "4" vs "userId" : 4

**Comment by sunshinejr** [comment]
Yeah, common case when dealing with API. Thanks for the issue anyways, good job with fixing the problem! 👏💯
